### ISSUE TITLE
It seems evm on Travis Ubuntu Trusty lacks thread support

### ISSUE THREAD

**Issue by cjohansson** [rejeep/evm#119]
Running this inside emacs 25 and above should eval to t but for emacs built via EVM it seems to eval to nil: `(fboundp 'make-thread)`

Is it possible to enable thread support for EVM?

**Comment by rejeep** [comment]
`(fboundp 'make-thread)` evals to `t` for me (I'm using `emacs-git-snapshot`)

**Comment by cjohansson** [comment]
Ok can you see what I have done wrong with this [travis config using evm](https://travis-ci.org/cjohansson/emacs-ssh-deploy/jobs/522032584#L914)

[Here is my travis file](https://github.com/cjohansson/emacs-ssh-deploy/blob/master/.travis.yml)
```
language: emacs-lisp

dist: trusty
before_install:
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip

env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-git-snapshot-travis

matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis

script:
  - emacs -Q --batch --eval '(message (emacs-version))'
  - make test
```

[And my elisp:](https://github.com/cjohansson/emacs-ssh-deploy/blob/master/ssh-deploy-test.el#L374)
```
(let (async-threads (fboundp 'make-thread))
      (if async-threads
          (message "\nNOTE: Running tests for asynchronous threads as well since it's loaded\n")
(message "\nNOTE: Skipping tests for asynchronous threads since it's not loaded\n")))
```
